S02 healthbar
WildCodeSchool/orleans-js-0920-p2-hero-game pull request #15
Opened 2020-11-12 15:12 UTC by florentdesmarets

2020-11-12 16:06 UTC, thomas-ode approved these changes

2020-11-12 17:47 UTC, ldupas requested changes

2020-11-12 17:47 UTC, ldupas commented on src/components/centralCards/CentralCards.jsx
> +import Logo_Entier from '../assets/Logo_Entier.png'
nom du logo à passer en anglais

2020-11-13 08:24 UTC, ldupas approved these changes
Ok

2020-11-13 08:25 UTC, merged