S03_US14_dammage
WildCodeSchool/orleans-js-0920-p2-hero-game pull request #17
Opened 2020-11-13 08:52 UTC by MartyLucas45

2020-11-13 12:02 UTC, florentdesmarets approved these changes

2020-11-16 08:22 UTC, ldupas requested changes

2020-11-16 08:22 UTC, ldupas commented on src/components/centralCards/CentralCards.jsx
> +            const tab1 = [
changer le nom de vos tableaux par des variables en anglais plus explicites

2020-11-16 08:22 UTC, ldupas commented on src/components/centralCards/CentralCards.jsx
> +            const tab3 = [
idem

2020-11-16 08:22 UTC, ldupas commented on src/components/centralCards/CentralCards.jsx
> +            const tab2 = [
idem

2020-11-16 08:52 UTC, ldupas approved these changes

2020-11-16 08:52 UTC, merged