game rules
WildCodeSchool/orleans-js-0920-p2-hero-game pull request #22
Opened 2020-11-24 15:57 UTC by Sylvie-Saidi

2020-11-24 16:20 UTC, florentdesmarets approved these changes

2020-11-25 08:22 UTC, ldupas requested changes

2020-11-25 08:22 UTC, ldupas commented on src/components/Rules/Rules.css
> +
réagencer les espacements entre sélecteurs

un seul saut à la ligne

2020-11-25 08:22 UTC, ldupas commented on src/components/Rules/Rules.jsx
> +                                 <p>Commencez par sélectionner votre super héro dans le menu de sélection. Choisissez-le bien ! Ses caractéristiques sont présentées sur la carte, vous y trouverez son
héros*

2020-11-25 08:22 UTC, ldupas commented on src/components/Rules/Rules.jsx
> +                                 <p>Pour infliger des dégâts au héro adverse, cliquez tout simplement sur le sort d’attaque désiré situé sur la carte de votre héro. Il peut être judicieux de choisir
héros

2020-11-25 08:22 UTC, ldupas commented on src/components/Rules/Rules.jsx
> +                            Chaque héro a un type d'élément de prédilection bien défini. Il existe 4 types d’éléments :
héros

2020-11-25 08:22 UTC, ldupas commented on src/components/Rules/Rules.jsx
> +                            <li>Force</li>
revoir indentation, un cran supplémentaire pour les li

2020-11-25 10:15 UTC, ldupas approved these changes

2020-11-25 10:15 UTC, merged