S02 us11 elements reminder
WildCodeSchool/orleans-js-0920-p2-hero-game pull request #4
Opened 2020-11-04 06:57 UTC by Sylvie-Saidi

Réorganisation dossier Quizz + Ajout Elements Reminder du Jeu

2020-11-04 13:40 UTC, MartyLucas45 approved these changes

2020-11-04 13:59 UTC, ldupas requested changes

2020-11-04 13:59 UTC, ldupas commented on src/components/ElementsReminder/ElementsReminder.css
> +/*Responsive a faire plus tard en paysage, adapter en fonction des autres elements du jeu + display none la navbar*/
Pas de code commenté

2020-11-04 13:59 UTC, ldupas commented on src/components/ElementsReminder/ElementsReminder.jsx
> +<i class="fas fa-long-arrow-alt-right"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="long-arrow-alt-right" class="svg-inline--fa fa-long-arrow-alt-right fa-w-14" role="img" x
revoir indentation

2020-11-04 13:59 UTC, ldupas commented on src/components/ElementsReminder/ElementsReminder.jsx
> +<i class="fas fa-long-arrow-alt-left"><svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="long-arrow-alt-left" class="svg-inline--fa fa-long-arrow-alt-left fa-w-14" role="img" xmln
revoir indentation

2020-11-05 12:58 UTC, ldupas approved these changes

2020-11-05 12:58 UTC, merged