S02_US09_warrior-and-battle
WildCodeSchool/orleans-js-0920-p2-hero-game pull request #7
Opened 2020-11-04 11:22 UTC by MartyLucas45

2020-11-04 12:34 UTC, thomas-ode approved these changes

2020-11-04 14:01 UTC, ldupas requested changes

2020-11-04 14:01 UTC, ldupas commented on src/components/centralCards/CardChoose.js
> +function CardChoose() {
CardChosen ou CardChose

2020-11-04 14:01 UTC, ldupas commented on src/components/centralCards/CardChoose.js
> +function CardChoose() {
ou CardChoice

2020-11-04 14:22 UTC, Sylvie-Saidi approved these changes

2020-11-04 14:23 UTC, ldupas requested changes

2020-11-04 14:23 UTC, ldupas commented on src/components/centralCards/CardChoice.jsx
> +function CardChoose() {
tu as changé le nom du composant mais pas de la fonction !

2020-11-05 13:00 UTC, ldupas approved these changes

2020-11-05 13:32 UTC, merged